### ISSUE TITLE
NSMutableIndexSet *indexesToReload.

### ISSUE THREAD

**Issue by shannoga** [100grams/HGPageScrollView#1]
in your .h file it appears as NSMutableIndexSet *indexesToReload.
but you are allocating it as NSIndexSet.

Thanks any way
Great work

Shani

**Comment by 100grams** [comment]
Thanks Shani, I've changed it to NSMutableSet, although for the sake of this example viewController, it could have been declared as NSSet too. 
Commit ba7eec6.
Hope you find this code useful, and I'd sure appreciate more issues and/or pull requests...
